### ISSUE TITLE
Sunflower essay map

### ISSUE THREAD

**Issue by kristanmhanson** [JSTOR-Labs/plant-humanities#100]
I have two maps with fly-tos in my sunflower essay (around para. 10).

The first map should display a geojson for Marshall County TN (Q495448), but it's not showing up.

The subsequent two maps with geojson layers work just fine!

https://dev.visual-essays.app/JSTOR-Labs/plant-humanities/sunflower/?ref=develop

**Comment by rsnyder** [comment]
Fixed.
