### ISSUE TITLE
Heliconia essay manifest rotate

### ISSUE THREAD

**Issue by kristanmhanson** [JSTOR-Labs/plant-humanities#101]
Para. 5 of the heliconia essay displays three images that are all hosted in different places.

The center image is pulled from a Smithsonian manifest, and it needs to be rotated 90.

When I apply "rotate=90" to that image, the command is applied to the wrong one (the first image of the 3). Not sure how to fix!

https://dev.visual-essays.app/JSTOR-Labs/plant-humanities/heliconia/?ref=develop

https://www.si.edu/object/heliconia-chartacea-var-meeana-wj-kress:nmnhbotany_10305313?edan_q=heliconia%2Bchartacea%2Bmeeana&oa=1&edan_fq%5B0%5D=media_usage:CC0&destination=/search/collection-images&searchResults=1&id=nmnhbotany_10305313

**Comment by rsnyder** [comment]
This should now be fixed.
