### ISSUE TITLE
Add Wikidata entities for all essays and insert generated QID into essay ve-config tag

### ISSUE THREAD

**Issue by rsnyder** [JSTOR-Labs/plant-humanities#125]

**Comment by LeibCelnik** [comment]
Added Wikidata entities (`eid` and `about`) to ve-config tag for: banana, arbor vitae, dittany, mint, cacao, Carolina rice, turmeric, boxwood, cinnamon, dragon tree, watermelon, Heliconia, sunflower, cassava, and Pelargonium essays. (Peony to be updated with Wikidata entities once essay is ready and QID generated). 

`eid` and `about` added below `banner` for each essay.
