### ISSUE TITLE
Resizing the homepage tiles. 

### ISSUE THREAD

**Issue by shubhampokharel** [JSTOR-Labs/plant-humanities#13]

**Comment by rsnyder** [comment]
Shubham - Is this for resizing the thumbnail images or something other issue?

**Comment by shubhampokharel** [comment]
Sorry for late reply, this is for resizing the thumbnail size. Right now its 400 X 400 px, Desired size is 400 X 260 px

**Comment by rsnyder** [comment]
Index page thumbnails have been resized to 400x260
