### ISSUE TITLE
Citations on the images pane.

### ISSUE THREAD

**Issue by shubhampokharel** [JSTOR-Labs/plant-humanities#16]

**Comment by rsnyder** [comment]
Please elaborate.

**Comment by shubhampokharel** [comment]
I believe its about the citations/control panel design on the viewer. 
<img width="1154" alt="Screen Shot 2020-10-20 at 3 40 38 PM" src="https://user-images.githubusercontent.com/24394116/97031789-cdc74680-152e-11eb-8d89-5c13884990aa.png">
