### ISSUE TITLE
QID Blank pop-ups

### ISSUE THREAD

**Issue by kristanmhanson** [JSTOR-Labs/plant-humanities#160]
I noticed several instances of blank pop-ups when data should appear. I can't find a pattern in the ones with this issue.

Sunflower essay: Prince Bishop of Eichstatt; florets; herbarium [Odd b/c herbarium works in a different essay.]
<img width="1013" alt="Screen Shot 2021-03-08 at 3 15 18 PM" src="https://user-images.githubusercontent.com/67124996/110376514-48e25280-8021-11eb-80f4-01fc592cd66f.png">

Heliconia essay: Heliconia metallica; horticulturalists; ecosystems; Heliconia imbricata

Cassava essay: Cassava bread

Pelargonium essay: Asia Minor; South Africa; (ignore Donald McDonald)

**Comment by rsnyder** [comment]
This should be resolved.
