### ISSUE TITLE
Pelargonium annotations

### ISSUE THREAD

**Issue by kristanmhanson** [JSTOR-Labs/plant-humanities#169]
https://lab.plant-humanities.org/pelargonium/

Paragraph 19 -- annotations

I created annotations for the photograph using our stories tool (1 annotation per detail). The annotations were displaying correctly at the time of launch.

<img width="703" alt="Screen Shot 2021-04-12 at 7 09 34 PM" src="https://user-images.githubusercontent.com/67124996/114473891-1b11a000-9bc3-11eb-9ac3-41e4de613209.png">

**Comment by kristanmhanson** [comment]
The file with annotations is still in main.

 plant-humanities/pelargonium/f82cac90.json

**Comment by julia-ha** [comment]
Hi @kristanmhanson , the annotations are showing now.
