### ISSUE TITLE
Scrolling issues in Firefox

### ISSUE THREAD

**Issue by buchanana01** [JSTOR-Labs/plant-humanities#23]
I cannot scroll through the essay when I am on Firefox, but I can on Safari

**Comment by rsnyder** [comment]
I've confirmed this is a Firefox specific issue.  I'm bumping the severity to Priority level 1.

**Comment by rsnyder** [comment]
Firefox uses a different property for wheel delta in wheel events.  The code now looks for the FF property in addition to the one used in Chrome and Safari.
