### ISSUE TITLE
Network display problems in heliconia essay

### ISSUE THREAD

**Issue by kristanmhanson** [JSTOR-Labs/plant-humanities#25]
Heliconia essay, 2 network visualizations: https://visual-essays.app/kristanmhanson/plant-humanities/heliconia

I've run into the following issues following the dev to production update.

- The network visualizations are displayed against a black background.

- The first network does not display; though, if user clicks on "network" icon in upper left column it will display.

- The changes Julia made to the second network (with bird, bat, and bug icons) only display in Chrome (not Firefox).

- The essay only wants to load and display one network as active for both paragraphs. I have to scroll to an upper/lower section in order to make the non-visible network "active".

**Comment by julia-ha** [comment]
Hi @kristanmhanson , regarding the issue with the first network graph, have you tried taking the `primary` out of the code on line 87?
Like this: `<param ve-vis-network file="https://raw.githubusercontent.com/kristanmhanson/plant-humanities/develop/graphs/heliconia birds.tsv">`

**Comment by kristanmhanson** [comment]
Hi @julia-ha Thanks for this suggestion. I deleted the primary tag, but that didn't change the loading issue. Still wants to display only one network.

**Comment by rsnyder** [comment]
The 4th item in the list (network data not updating when moving between active paragraphs) should be fixed now. @julia-ha - please check/confirm the other issues have been resolved, and if so, close this issue.
