### ISSUE TITLE
Text not wrapping around inset image

### ISSUE THREAD

**Issue by kristanmhanson** [JSTOR-Labs/plant-humanities#28]
I really like the ability to have a small inset image in the text column. This feature introduces a new rhythm in the presentation of information to the reader and it can visualize a more explicit connection between left text and right image columns. It also provides an option to deal with OA images that are too low res for right column display.

With the upgrade, the text no longer wraps around the inset image in heliconia essay.
https://visual-essays.app/kristanmhanson/plant-humanities/heliconia

In the future, it would be ideal to be able to place the image at the beginning or middle of a paragraph.

**Comment by rsnyder** [comment]
Kristan - This should be working again.  The placement of the Markdown image tag is slightly different now in that a blank line between the Markdown image tag and the other paragraph text should no longer be used.  This update also allows inset images to be used anywhere in a paragraph, not just the beginning.

The use of an image caption is not working.  The component library used for this is doing something weird with captions and I haven't been able to find a solution.  For now avoid including captions.

Here's an updated sample essay with embedded images in the essay text - https://visual-essays.app/static-images
