### ISSUE TITLE
Zoom to image detail on click not working in heliconia essay

### ISSUE THREAD

**Issue by kristanmhanson** [JSTOR-Labs/plant-humanities#32]
There are zoom to links in the text for the first image--"sculptural bracts" and "banana-like leaves." The links now show details of the wrong portions of the image. 

This bug is not the case for an image of a distribution map later in the essay with zoom to links embedded in text--"central Mexico down to northern Argentina..." and "Samoa to New Guinea."

https://visual-essays.app/kristanmhanson/plant-humanities/heliconia

**Comment by julia-ha** [comment]
@kristanmhanson Hi Kristan, is this still an issue in the essay?
