### ISSUE TITLE
Missing Map Labels in Banana essay

### ISSUE THREAD

**Issue by alexbrymer** [JSTOR-Labs/plant-humanities#39]
This could be a question for @buchanana01, but should there be labels on the maps in the banana essay?  For example, the map next to para 5 beginning with "While bananas are more diverse that previously understood..." has overlays but no way to find out by clicking or hovering what those overlays are meant to indicate...

**Comment by alexbrymer** [comment]
Smae thing goes for the para starting "In 2002, a comprehensive study of relationships among wild and cultivated bananas..."

**Comment by alexbrymer** [comment]
It looks like some pins bring up our LOD overlay, but not all...

**Comment by buchanana01** [comment]
There are labels, but we are having an issue with them showing up. Ron is working on this!

**Comment by rsnyder** [comment]
Labels are now showing on Banana, and are generally able to be displayed on initial map load using the `show-labels` attribute on the `ve-map-layer` tag.
