### ISSUE TITLE
Rendering of multiple footnotes seems ... off

### ISSUE THREAD

**Issue by alexbrymer** [JSTOR-Labs/plant-humanities#40]
In Cacao, Rebecca has a number of footnotes where she has multiple sources for a single note, and those #s are all just presented concatenated, like 1112 for 11 & 12.  Perhaps we need a space between the footnotes, or put all references into a single footnote (not sure what our style says to do).

**Comment by buchanana01** [comment]
I wrote her an email and asked if she could address this. She is going to separate all of them to conform to Chicago style, which is what we will be using going forward. So we shouldn't have this issue in the future.... only scientists do their footnotes like this lol.

**Comment by alexbrymer** [comment]
Ha!  Scientists.  <shakes head>

**Comment by buchanana01** [comment]
Ok Rebecca fixed the footnotes super fast like a boss!
