### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by alexbrymer** [JSTOR-Labs/plant-humanities#65]

**Comment by jaith** [comment]
When would you like this done by?

**Comment by alexbrymer** [comment]
before we release the public beta?  I think we're currently targeting Jan for that.

**Comment by rsnyder** [comment]
FYI.  There is already a GA tag defined that broadly covers all visual essay requests, including non-PH.

**Comment by jaith** [comment]
so that tag Ron mentions probably covers page views. If you want specific events tracked, let me know. @alexbrymer @shubhampokharel and I guess it matters for Ron's codebase purposes whether this needs to be tracked on all visual essays or just plants

**Comment by alexbrymer** [comment]
I see a Visual Essays app in google analytics, but no usage within it.  Should i see usage?

I don't mind PH page views being visible in the same app as generic essays, but it would be good to be able to drill down to just PH -- is that possible? It's hard to see without any usage data...

**Comment by jaith** [comment]
![image](https://user-images.githubusercontent.com/5766242/100136326-e80b8180-2e58-11eb-9238-de3eff09a99d.png)
I see use that WAS in Visual Essays, but it stopped recording on October 22nd. Maybe @rsnyder knows what happened at that time or if there was a refactor that affected it.

**Comment by jaith** [comment]
Making a note here to say I didn't forget this, but I probably need a little info from Ron to proceed since the relationship between various codebases is complex and evolving, and I wouldn't know where to work

**Comment by jaith** [comment]
Hey I got this working (with yet another new property, Ron UA-125778965-6) 
#
There it is live tracking me
![image](https://user-images.githubusercontent.com/5766242/109892781-985b0400-7c58-11eb-9b31-06741c62f287.png)

**Comment by jaith** [comment]
look in the Visual-Essays GA property. If you want a separate one, let me know. This is tracking page views, but no specific events. Assuming we want the usual additional view created that filters out ITHAKA traffic?
