### ISSUE TITLE
Unstable ve-storiiies tags

### ISSUE THREAD

**Issue by WouterKlein** [JSTOR-Labs/plant-humanities#86]
In the dragon tree essay, there are 3 visualizations with ve-storiiies tags, which are very shaky (literally), and apparently they have annotations of some sort, that are shown by default.

The ve-storiiies ids are:
8a1g2
751f7
7b1dr

The latest version of the esaay is on https://visual-essays.app/develop/WouterKlein/plant-humanities/dragon_tree

**Comment by rsnyder** [comment]
What do you mean by "shaky"?
