### ISSUE TITLE
IIIF images are not shown

### ISSUE THREAD

**Issue by WouterKlein** [JSTOR-Labs/plant-humanities#89]
In the dragon tree essay, the last two paragraphs have IIIF images that are not shown. The images were made at https://free.iiifhosting.com, as shown in the "iiif-url" attribute.

The latest version of the dragon tree essay is here: https://visual-essays.app/develop/WouterKlein/plant-humanities/dragon_tree

**Comment by julia-ha** [comment]
https://visual-essays.app/develop/WouterKlein/plant-humanities/dragon_tree

**Comment by julia-ha** [comment]
Hi @WouterKlein , when using a IIIF image URL and not a IIIF manifest, the value of the url attribute must end with `/info.json`. So for example, `<param ve-image fit="contain" url="https://free.iiifhosting.com/iiif/31fb222aa31e439323c29d61cb363d5c897b02d8cde694ff946f0f6adbb00ad">` should be `<param ve-image fit="contain" url="https://free.iiifhosting.com/iiif/31fb222aa31e439323c29d61cb363d5c897b02d8cde694ff946f0f6adbb00ad/info.json">`

The `iiif-url` attribute is still valid but the updated code handles all sources with the `url` attribute so you can use that instead. The fixes are made in the jstor-labs/plant-humanities repo so you can view the code there for reference and see the images show up on https://plant-humanities.app/dragon_tree/.

**Comment by WouterKlein** [comment]
Hi @julia-ha, thanks for the update, now I can see the iiif images on https://plant-humanities.app/dragon_tree/.
I'm reopening this issue, however, because I cannot see the images in develop mode (where I'm making changes): https://plant-humanities.app/dragon_tree/?ref=develop.

**Comment by julia-ha** [comment]
Hi @WouterKlein, the changes right now to make the images visible are in the main branch. You can edit the `<param ve-image>` tags in the develop version following my comment above or viewing the code on the main branch here: https://github.com/JSTOR-Labs/plant-humanities/blob/main/dragon_tree.md (lines 93 and 98) for reference to fix it. Let me know if there are any questions.
